"""Add lesson day association to student

Revision ID: 10d2da218a1
Revises: b4940689ca
Create Date: 2015-11-05 18:27:21.885608

"""

# revision identifiers, used by Alembic.
revision = '10d2da218a1'
down_revision = 'b4940689ca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('lesson_day_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'lesson_days', ['lesson_day_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'lesson_day_id')
    ### end Alembic commands ###
