"""Associating student with grade

Revision ID: 187ed5b5bb2
Revises: 3f0f1fb496f
Create Date: 2015-11-01 16:16:23.914205

"""

# revision identifiers, used by Alembic.
revision = '187ed5b5bb2'
down_revision = '3f0f1fb496f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('grade_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'grades', ['grade_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'grade_id')
    ### end Alembic commands ###
