"""Add current day

Revision ID: 1982b2294bf
Revises: 10d2da218a1
Create Date: 2015-11-08 18:40:37.923658

"""

# revision identifiers, used by Alembic.
revision = '1982b2294bf'
down_revision = '10d2da218a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('schedule_day_id', sa.Integer(), nullable=True),
    sa.Column('lessod_day_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lessod_day_id'], ['lesson_days.id'], ),
    sa.ForeignKeyConstraint(['schedule_day_id'], ['schedule_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('current_day')
    ### end Alembic commands ###
