"""Add subjects

Revision ID: 35ef8baea55
Revises: 187ed5b5bb2
Create Date: 2015-11-01 17:29:28.580002

"""

# revision identifiers, used by Alembic.
revision = '35ef8baea55'
down_revision = '187ed5b5bb2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subject')
    ### end Alembic commands ###
