"""Add grades

Revision ID: 3f0f1fb496f
Revises: 42c881394eb
Create Date: 2015-11-01 15:49:53.458324

"""

# revision identifiers, used by Alembic.
revision = '3f0f1fb496f'
down_revision = '42c881394eb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grade')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grades')
    ### end Alembic commands ###
