"""Add periods

Revision ID: 5558b617758
Revises: 1656bc5bfbe
Create Date: 2015-11-02 20:18:04.679682

"""

# revision identifiers, used by Alembic.
revision = '5558b617758'
down_revision = '1656bc5bfbe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('periods')
    ### end Alembic commands ###
