"""Adding schedules

Revision ID: 75569aeead
Revises: 124f917597c
Create Date: 2015-11-03 21:26:30.693097

"""

# revision identifiers, used by Alembic.
revision = '75569aeead'
down_revision = '124f917597c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('schedule_day_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_day_id'], ['schedule_days.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'section_id', 'schedule_day_id')
    )
    op.create_index(op.f('ix_schedules_schedule_day_id'), 'schedules', ['schedule_day_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedules_schedule_day_id'), table_name='schedules')
    op.drop_table('schedules')
    ### end Alembic commands ###
