"""Add lesson days

Revision ID: b4940689ca
Revises: 75569aeead
Create Date: 2015-11-05 18:20:47.795446

"""

# revision identifiers, used by Alembic.
revision = 'b4940689ca'
down_revision = '75569aeead'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_days')
    ### end Alembic commands ###
